# Generated by Django 3.2.12 on 2023-03-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20230316_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='visiblity',
            field=models.BooleanField(default=False),
        ),
    ]
