# Generated by Django 3.2.12 on 2023-03-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20230317_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default_profile_image.jpg', upload_to='profile_images_dir/'),
        ),
    ]
